require('core.options')
require('core.keybindings')

require('plugins.packer')
require('plugins.lualine')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.bufferline')
require('plugins.lsp')
-- require('plugins.vim-airline')
require('plugins.dap')
require('plugins.dapui')
